services:
  database:
    image: bitnami/postgresql:16.2.0
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - ask-me-anything_net

volumes:
  postgresql_data:
    driver: local

networks:
  ask-me-anything_net:
